#! /bin/sh

sxhkd &

bspc monitor DP-2-2 -d 1 2 3
bspc monitor DP-1 -d 4 5 6 7
bspc monitor DP-2-1 -d 8 9 0

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

