#! /bin/sh
killall sxkkd & sxhkd &
bspc monitor 				HDMI-1 -d I II III IV V
bspc monitor 				DP-1 -d VI VII VIII IX X
bspc config border_width         	2
bspc config window_gap          	30

bspc config split_ratio          	0.52
bspc config borderless_monocle   	true
bspc config gapless_monocle      	true

bspc config click_to_focus 		button1
bspc config focus_follows_pointer	true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

fix_fucking_java
